GET http://localhost:3001/api/tasks

###
GET http://localhost:3001/api/tasks/7

###
POST http://localhost:3001/api/tasks/7
content-type: application/json

{
  "status": "1"
}

###
POST http://localhost:3001/api/tasks/
content-type: application/json

{
  "data": {
    "title": "Sent via HTTP request 4",
    "description": "N/A",
    "assignee": 1,
    "due_date": "2024-09-25T15:54:39.923Z"
  }
}
